spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: validate

security:
  jwt:
    token:
      access-secret-key: ${JWT_ACCESS_SECRET_KEY}
      refresh-secret-key: ${JWT_REFRESH_SECRET_KEY}

server:
  tomcat:
    accept-count: 200
