spring:
  datasource:
    hikari:
      read:
        jdbc-url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
      write:
        jdbc-url: ${SPRING_WRITER_DATASOURCE_URL}
        username: ${SPRING_WRITER_DATASOURCE_USERNAME}
        password: ${SPRING_WRITER_DATASOURCE_PASSWORD}
  jpa:
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: validate

security:
  jwt:
    token:
      access-secret-key: ${JWT_ACCESS_SECRET_KEY}
      refresh-secret-key: ${JWT_REFRESH_SECRET_KEY}

storage:
  path: /uploads
  redirectUrl: image.chongdae.site