### 로그인 API
POST {{base-url}}/auth/login
Content-Type: application/json

{
  "ci": "dora1234"
}

### 회원가입 API
POST {{base-url}}/auth/signup
Content-Type: application/json

{
  "ci": "poke12345678"
}

### 토큰 재발급 API
POST {{base-url}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzI0MTMwODY0fQ.BoN2p--HbWn1zbed2NSZtZm4RumWtVm338sAtxXwEC8"
}
