name: Android CI CD

on:
  pull_request:
    branches:
      - "develop"
      - "release*"

    paths: ["android/**"]


jobs:
  ktlint_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Create google-services
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > ./android/app/google-services.json

      - name: Create local.properties
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          TOKEN: ${{ secrets.TOKEN }}
          NATIVE_APP_KEY: ${{ secrets.NATIVE_APP_KEY }}
        run: |
          echo "sdk.dir=/Users/chaehyun/Library/Android/sdk" > ./android/local.properties
          echo "base_url=$BASE_URL" >> ./android/local.properties
          echo "token=$TOKEN" >> ./android/local.properties
          echo "native_app_key=$NATIVE_APP_KEY" >> ./android/local.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./android/gradlew

      - name: Ktlint check
        run: |
          cd ./android
          ./gradlew ktlintCheck

  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Create google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$GOOGLE_SERVICES_JSON" > ./android/app/google-services.json

      - name: Create local.properties
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          TOKEN: ${{ secrets.TOKEN }}
          NATIVE_APP_KEY: ${{ secrets.NATIVE_APP_KEY }}
        run: |
          echo "sdk.dir=/Users/chaehyun/Library/Android/sdk" > ./android/local.properties
          echo "base_url=$BASE_URL" >> ./android/local.properties
          echo "token=$TOKEN" >> ./android/local.properties
          echo "native_app_key=$NATIVE_APP_KEY" >> ./android/local.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./android/gradlew

      - name: Gradle Clean check
        run: ./android/gradlew clean

      - name: Build with Gradle
        run: ./android/gradlew build

      - name: Run Unit Test
        run: ./android/gradlew test

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test
    if: startsWith(github.event.pull_request.base.ref, 'release-')
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./android/gradlew

      - name: Create google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo "$GOOGLE_SERVICES_JSON" > ./android/app/google-services.json

      - name: Create service_account.json
        id: createServiceAccount
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > ./android/app/service_account.json

      - name: Set up environment variable for BuildConfig
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          TOKEN: ${{ secrets.TOKEN }}
          NATIVE_APP_KEY: ${{ secrets.NATIVE_APP_KEY }}
        run: |
          echo "base_url=$BASE_URL" >> ./android/local.properties
          echo "token=$TOKEN" >> ./android/local.properties
          echo "native_app_key=$NATIVE_APP_KEY" >> ./android/local.properties

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build release AAB
        run: ./android/gradlew bundleRelease

      - name: Sign AAB
        id: sign
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: ./android/app/build/outputs/bundle/release
          output: ./android/build/release/signed
          signingKeyBase64: ${{ secrets.ENCODED_KEYSTORE }}
          alias: ${{ secrets.AN_ALIAS }}
          keyStorePassword: ${{ secrets.AN_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.AN_KEY_PASSWORD }}

      - name: Upload AAB to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.zzang.chongdae
          releaseFiles: ./android/app/build/outputs/bundle/release/app-release.aab
          track: "총대마켓 - 비공개 테스트"
