name: Auto Close Issues on Merge

on:
  pull_request:
    types: [closed]

jobs:
  close-related-issue:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.base.ref != 'main'
    steps:
      - name: Extract and Close Issue
        run: |
          PR_BODY="${{ github.event.pull_request.body }}"
          ISSUE_NUMBERS=$(echo $PR_BODY | grep -oP 'close #\d+' | awk '{print substr($2, 2)}')
          for ISSUE_NUMBER in $ISSUE_NUMBERS; do
            gh api -X PATCH /repos/${{ github.repository }}/issues/$ISSUE_NUMBER --field state=closed
          done
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_CLOSE_GITHUB_TOKEN }}
